#!/bin/bash

./compile

if [ $1 -eq 'staging' ]
then
    SERVER=( 'caerphoto.com' )
else
    SERVER=( 'caerphoto-staging' )
fi

DEPLOY_PATH=/var/www/bounty_tracker
REPO=git://github.com/caerphoto/bounty_tracker.git
USER=deploy

ENVIRONMENT=${1:-"production"}
REF=${2:-"node-rewrite"}

trap 'test -n "$SUCCESS" || echo "  error: aborted"' EXIT
echo "* Deploying $ENVIRONMENT/$REF"

ssh $USER@$SERVER "cd $DEPLOY_PATH && \
                   git reset --hard && \
                   git checkout $REF && \
                   git pull && \
                   npm install && \
                   /etc/init.d/bounty_tracker stop"

SUCCESS=true
